export const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const defaultData = () => ({
  income: "",
  currentSavings: "",
  categories: [],
  transactions: [],
  bills: [],
});

export const C = {
  bg: "var(--color-bg)",
  surface: "var(--color-surface)",
  surfaceAlt: "var(--color-surface-alt)",
  border: "var(--color-border)",
  borderHover: "var(--color-border-hover)",
  blue: "var(--color-blue)",
  blueDark: "var(--color-blue-dark)",
  blueLight: "var(--color-blue-light)",
  blueMid: "var(--color-blue-mid)",
  gold: "var(--color-gold)",
  goldDark: "var(--color-gold-dark)",
  goldLight: "var(--color-gold-light)",
  green: "var(--color-green)",
  greenLight: "var(--color-green-light)",
  red: "var(--color-red)",
  redLight: "var(--color-red-light)",
  orange: "var(--color-orange)",
  orangeLight: "var(--color-orange-light)",
  text: "var(--color-text)",
  textMid: "var(--color-text-mid)",
  textLight: "var(--color-text-light)",
  white: "var(--color-white)",
};
